import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, Stack, Box } from "@mui/material";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>MyShop - Main</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Image src="/Brooklyn.jpg" alt="Vercel Logo" width={"100vw"} height={"100vh"}/> */}
        <Box
          style={{
            backgroundImage: `url("/Brooklyn.jpg")`,
            backgroundRepeat: "no-repeat",
            backgroundSize:"cover",
            filter: "grayscale(35%)"
          }}
          sx={{
            width: "100vw",
            height: "70vh",
            backgroundColor: "primary.dark",
            boxShadow:3,
          }}
          className="unset-img"
        >
        
        </Box>
      </main>

      
    </div>
  );
};

export default Home;
