import { Button, Flex, Heading, Text,Box, VStack } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/shared/Navbar";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nombre tienda - Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar/>

        <VStack
          w="100vw"
          h="70vh"
          minH={"600px"}
          bgColor="gray.600"
          bgRepeat="no-repeat"
          bgSize={"cover"}
          alignItems={"center"}
          justifyContent="center"
          p="10"
        >
          <Box w="80%" textAlign={"left"} h="50%">

            <Heading color="white" fontSize={"5xl"}>Encuentra tu ropa de calidad solo en </Heading> {' '}
            <Heading fontSize={"6xl"}>Nombre tienda</Heading>
            <Text fontSize={"2xl"} color="whiteAlpha.800">Productos únicos,<br/> traidos directamente de la mano de los mejores fabricantes</Text>
          </Box>
        </VStack>
      </main>
    </div>
  );
};

export default Home;
